#!/bin/bash



pandoc  -o paseos-por-venecia.docx \
        --metadata title="Paseos por Venecia" --metadata creator="JJ Merelo" --metadata rights="CC-BY-SA 3.0" \
        ../paseos-por-venecia.txt  *.md




