#!/bin/bash

# Cambia la plantilla de latex al directorio donde esté

pandoc --verbose --template="$PWD"/plantilla.latex \
    -V language=spanish -V lang=es-ES \
    -V author='JJ Merelo' -V title='Paseos por Venecia'\
    -V documentclass=book\
    -o paseos-por-venecia.pdf \
    texto/*.md \
    --toc



